server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://product-db:5432/products
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest